#%RAML 1.0 NamedExample
info-example:
  creation_time: 1
  name: "Analytics Extensions API using MuleSoft"
  descritpion: "A live demo of an analytics extension service using MuleSoft"
  server_version: "1.0.0"
  state_path: "http://tableau-extension.us-e1.cloudhub.io/"
  versions:
    v1:
      features:
        authentication:
          methods:
            basic-auth: {}
          required: true
